hydra:
  run:
    dir: ${save_path}


save_path: ${path}/OT_${now:%Y_%m_%d}_${now:%H_%M_%S_%f}_${target_distribution}_${cvx_dim}_${noncvx_dim}

path: outputs/OT/${cvx_dim}d/

device: cuda

multi_clf: data/qcd_scores.h5

conds_trans: log
bootstrap: false

cvx_dim: 3
noncvx_dim: 1

target_distribution: source # base or source have to add uniform/normal/dirichlet/base_normal
train_args:
  nepochs: 100
  lr_f: 0.001
  lr_g: 0.001
  epoch_size: 8 # number of iteration per epoch
  datatype: "" # prob
  f_per_g: 4
  g_per_f: 10
  burn_in: 50
  batch_size: 1024
  loss_li_ratio: 0.0
  loss_wasser_ratio: 1.0
  grad_norm:
    f: 0
    g: 0
  learning_rate_scheduler: true


model_args:
  cvx_dim: ${cvx_dim}
  noncvx_dim: ${noncvx_dim}
  nonconvex_activation: "softplus_zeroed" # quadlrelu
  convex_activation: "softplus_zeroed" #quadlrelu
  correction_trainable: true
  first_act_sym: "no" #"symsoftplus"
  logit: true
  nonconvex_layersizes: 8
  convex_layersizes: 64
  n_layers: 4
  device: ${device}
  verbose: true
  noncvx_norm: standard_first
  cvx_norm: ""


